WordBank/urls.py
from django.conf.urls import url

from . import views

app_name = 'WordBank'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^result/$', views.result, name='result'),
    url(r'^addword/$', views.addword, name='addword'),
    url(r'^allword/$', views.allword, name='allword'),
    url(r'^backupandrestore/$', views.backup_and_restore, name='backupandrestore'),
    url(r'^showlastsearchkeyword/$', views.showLastSearchKeyword, name='showlastsearchkeyword'),
    url(r'^showmostsearchword/$', views.showMostSearchWord, name='showmostsearchword'),
]

WordBankWebsite/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^wordbank/', include('WordBank.urls')),
    url(r'^$', include('WordBank.urls')),
    url(r'^admin/', admin.site.urls),
]

WordBank/models.py
from django.db import models

class Word(models.Model):
	word_text = models.CharField(max_length=100)
	def __str__(self):
		return self.word_text

class WordType(models.Model):
	word = models.ForeignKey(Word, on_delete=models.CASCADE)
	word_type = models.CharField(max_length=15)
	def __str__(self):
		return "{} ({})".format(self.word.word_text,self.word_type)

class WordMeaning(models.Model):
	type = models.ForeignKey(WordType, on_delete=models.CASCADE)
	word_meaning = models.CharField(max_length=200)
	def __str__(self):
		return "{} ({}) = {}".format(self.type.word.word_text,self.type.word_type,self.word_meaning)

class WordExample(models.Model):
	meaning = models.ForeignKey(WordMeaning, on_delete=models.CASCADE)
	word_example = models.CharField(max_length=200)
	def __str__(self):
		return "{} ({}) ex. {}".format(self.meaning.type.word.word_text,self.meaning.type.word_type,self.word_example)


	

WordBank/views.py
from django.shortcuts import render
from django.http import HttpRequest , HttpResponse , HttpResponseRedirect
from django.template import loader
from django.core.urlresolvers import reverse
from django.core.files.storage import default_storage
from django.utils.encoding import smart_str
from wsgiref.util import FileWrapper
from django.utils import timezone

import csv , os , time , datetime
from xml.etree import ElementTree as ET

from .models import Word , WordType , WordMeaning , WordExample

def index(request):
	return render(request, 'WordBank/index.html', {})

def result(request):
	searchWord = request.GET['wordInput']
	searchMethod = request.GET['searchMethod']
	if searchMethod == "any":
		wordList = Word.objects.filter(word_text__contains=searchWord)
	elif searchMethod == "startWith":
		wordList = Word.objects.filter(word_text__startswith=searchWord)
	else:
		searchList = Word.objects.filter(word_text__startswith=searchWord)
		wordList = []
		for w in searchList:
			if w.word_text == searchWord:
				wordList.append(w)

	# save last search keyword
	lastSearchDirPath = 'WordBank/'
	lastSearchFileName = 'lastSearchKeyword'
	tree = ET.parse('{}{}.xml'.format(lastSearchDirPath,lastSearchFileName))
	root = tree.getroot()
	keyword_ele = ET.SubElement(root, "Search_Keyword")
	keyword_ele.text = searchWord
	time_ele = ET.SubElement(keyword_ele, "Search_Time")
	time_ele.text = "{}/{}/{}".format(timezone.now().day,timezone.now().month,timezone.now().year)
	wordFoundCount_ele = ET.SubElement(keyword_ele, "Found")
	wordFoundCount_ele.text = "{} words".format(len(wordList))
	foundWord_ele = ET.SubElement(keyword_ele, "Found_Word")
	foundWordList = [] #for most search word
	for w in wordList:
		wordFound_ele = ET.SubElement(foundWord_ele, "Word")
		wordFound_ele.text = w.word_text
		foundWordList.append(w.word_text)
	#save most search word
	mostSearchDirPath = 'WordBank/'
	mostSearchFileName = 'mostSearchWord'
	mostSearchTree = ET.parse('{}{}.xml'.format(mostSearchDirPath,mostSearchFileName))
	mostSearchRoot = mostSearchTree.getroot()
	updatedSearchWordList = []
	print(foundWordList)
	for word in mostSearchRoot:
		for foundWord in foundWordList:
			if word.text == foundWord:
				searchTimes_ele = word.find("searchTimes")
				newSearchTimes = int(searchTimes_ele.text) +1
				searchTimes_ele.text = str(newSearchTimes)
				updatedSearchWordList.append(foundWord)
	print(updatedSearchWordList)
	for updatedSearchWord in updatedSearchWordList:
		foundWordList.remove(updatedSearchWord)
	print(foundWordList)
	for unupdateSearchWord in foundWordList:
		word_ele = ET.SubElement(mostSearchRoot, "word")
		word_ele.text = unupdateSearchWord
		searchTimes_ele = ET.SubElement(word_ele, "searchTimes")
		searchTimes_ele.text = "1"
	with open("{}{}.xml".format(mostSearchDirPath,mostSearchFileName), 'wb') as xmlfile:
		mostSearchTree.write(xmlfile, encoding='utf-8')
	# keep only last ten search keyword
	for searchKeyword in root:
		if len(root.findall("Search_Keyword")) > 10:
			root.remove(searchKeyword)
	with open("{}{}.xml".format(lastSearchDirPath,lastSearchFileName), 'wb') as xmlfile:
		tree.write(xmlfile, encoding='utf-8')

	return render(request, 'WordBank/result.html', {'wordInput':searchWord , 'wordList':wordList})

def getLastSearchKeyword(request):
	lastSearchDirPath = 'WordBank/'
	lastSearchFileName = 'lastSearchKeyword'
	tree = ET.parse('{}{}.xml'.format(lastSearchDirPath,lastSearchFileName))
	

def addword(request):
	context = {'message_add':'','message_upload':''}
	if request.method == 'POST':
		if request.FILES == {}:
			word = request.POST["word"]
			typ = request.POST["wordType"]
			meaning = request.POST["wordMeaning"]
			examples = request.POST["wordExample"]
			examples = examples.split("\n")
			if word!=''or meaning!='': #empty fill
				if Word.objects.filter(word_text=word): #if have word
					word_add = Word.objects.get(word_text=word) #get word
				else: #if not have word
					word_add = Word(word_text=word) #create new word
				word_add.save()
				if word_add.wordtype_set.filter(word_type__startswith=typ): #if have typ
					word_add_type = word_add.wordtype_set.get(word_type=typ) #get type
				else: #if not have type
					word_add_type = word_add.wordtype_set.create(word_type=typ) #create new type
				word_add_type.save()
				if word_add_type.wordmeaning_set.filter(word_meaning__startswith=meaning): #if have typ
					word_add_meaning = word_add_type.wordmeaning_set.get(word_meaning=meaning) #get type
				else: #if not have type
					word_add_meaning = word_add_type.wordmeaning_set.create(word_meaning=meaning) #create new type
				word_add_meaning.save()
				old_word_example_list = word_add_meaning.wordexample_set.all()
				for example in examples:
					if example != "":
						isNotHaveExample = True
						for oldexample in old_word_example_list:
							if example == oldexample.word_example:
								isHaveExample = False
						if isNotHaveExample:
							word_add_example = word_add_meaning.wordexample_set.create(word_example=example)
							word_add_example.save()
				context = {'message_add':'Add word success','message_upload':''}
			else:
				context = {'message_add':'Please fill input','message_upload':''}
		elif request.POST['submit'] == "Upload CSV File":
			context = upload_word_csv(request)
		elif request.POST['submit'] == "Upload XML File":
			context = upload_word_xml(request)
	return render(request, 'WordBank/addword.html',context)

def allword(request):
	wordList = Word.objects.filter(word_text__startswith="")
	return render(request, 'WordBank/allword.html', {'wordList':wordList})

def upload_word_csv(request,csvfilename='word_data'):
	if csvfilename == 'word_data':
		dirPath = 'WordBank/wordCSV/'
		csvFile = request.FILES['csvFile']
		saveFilePath = default_storage.save(dirPath, csvFile)
		os.rename(saveFilePath,"{}word_data.csv".format(dirPath))
	else:
		dirPath = 'WordBank/backup/'
	with open("{}{}.csv".format(dirPath,csvfilename),encoding='utf-8') as csvfile:
		dataReader = csv.DictReader(csvfile)
		word_add = None
		word_add_type = None
		word_add_meaning = None
		word_add_example = None
		for row in dataReader:
			if row["Word"] != "":
				word = row["Word"]
				if Word.objects.filter(word_text=word): #if have word
					word_add = Word.objects.get(word_text=word) #get word
				else: #if not have word
					word_add = Word(word_text=word) #create new word
				word_add.save()
			if row["Type"] != "":
				typ = row["Type"]
				if word_add.wordtype_set.filter(word_type__startswith=typ): #if have typ
					word_add_type = word_add.wordtype_set.get(word_type=typ) #get type
				else: #if not have type
					word_add_type = word_add.wordtype_set.create(word_type=typ) #create new type
				word_add_type.save()
			if row["Meaning"] != "":
				meaning = row["Meaning"]
				if word_add_type.wordmeaning_set.filter(word_meaning__startswith=meaning): #if have typ
					word_add_meaning = word_add_type.wordmeaning_set.get(word_meaning=meaning) #get type
				else: #if not have type
					word_add_meaning = word_add_type.wordmeaning_set.create(word_meaning=meaning) #create new type
				word_add_meaning.save()
			if row["Example Sentences"] != "":
				example = row["Example Sentences"]
				if not(word_add_meaning.wordexample_set.filter(word_example__startswith=example)):
					word_add_example = word_add_meaning.wordexample_set.create(word_example=example)
					word_add_example.save()
	context = {'message_add':'','message_upload_csv':'Upload word success'}
	return context

def upload_word_xml(request):
	dirPath = 'WordBank/temp/'
	xmlFile = request.FILES['xmlFile']
	saveFilePath = default_storage.save(dirPath, xmlFile)
	os.rename(saveFilePath,"{}word_upload.xml".format(dirPath))
	tree = ET.parse('{}word_upload.xml'.format(dirPath))
	root = tree.getroot()
	for w in root:
		word = w.attrib['text']
		if Word.objects.filter(word_text=word): #if have word
			word_add = Word.objects.get(word_text=word) #get word
		else:
			word_add = Word(word_text=word)
			word_add.save()
		for t in w:
			typ = t.attrib['text']
			if word_add.wordtype_set.filter(word_type__startswith=typ): #if have typ
				word_add_type = word_add.wordtype_set.get(word_type=typ) #get type
			else:
				word_add_type = word_add.wordtype_set.create(word_type=typ)
				word_add_type.save()
			for m in t:
				meaning = m.attrib['text']
				if word_add_type.wordmeaning_set.filter(word_meaning__startswith=meaning): #if have typ
					word_add_meaning = word_add_type.wordmeaning_set.get(word_meaning=meaning) #get type
				else:
					word_add_meaning = word_add_type.wordmeaning_set.create(word_meaning=meaning)
					word_add_meaning.save()
				for e in m:
					example = e.text
					if not(word_add_meaning.wordexample_set.filter(word_example__startswith=example)):
						word_add_example = word_add_meaning.wordexample_set.create(word_example=example)
						word_add_example.save()
	context = {'message_add':'','message_upload_xml':'Upload word success'}
	return context

def backup_and_restore(request):
	context = {'message_backup':'','message_restore':'','backup_list':''}
	if request.method == 'POST':
		if request.POST != {}:
			for keys in request.POST.keys():
				if keys == 'backup_csv':
					context = backup(request,'csv')
				elif keys == 'backup_xml':
					context = backup(request,'xml')
				elif keys == 'restore':
					context = restore(request)
				elif keys == 'export':
					return export(request)
				elif keys == 'convertXMLstandard':
					return convertXMLstandard(request)
	#load restore list
	dirPath = 'WordBank/backup/'
	backupList = []
	for file in os.listdir(dirPath):
		filename = file.split("_")
		date = filename[0]
		time = filename[1]
		backupName = ''
		for i in range(2,len(filename)):
			backupName = "{}{}".format(backupName,filename[i])
		#correct format for display file name
		date = date.split('-')
		time = time.split('-')
		backupName = backupName.split('.')
		name=''
		for i in range(len(backupName)-1):
			name = "{}{}".format(name,backupName[i])

WordBank/templates/WordBank/addword.html
<html>
<head>
<title>Word Bank Website</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'WordBank/style.css' %}" />
</head>
<body>

<h1>Add Word</h1>

<form action="{% url 'WordBank:addword' %}" method="post">
{% csrf_token %}
Word : <input type="text" name="word" maxlength="100"><br><br>
Type : <select name="wordType" id='wordType'>
    	<option value="Noun">Noun</option>
	<option value="Pronoun">Pronoun</option>
	<option value="Verb">Verb</option>
	<option value="Adverb">Adverb</option>
	<option value="Adjective">Adjective</option>
	<option value="Preposition">Preposition</option>
	<option value="Conjunction">Conjunction</option>
	<option value="Interjection">Interjection</option>
       </select><br><br>
Meaning : <input type="text" name="wordMeaning" maxlength="200"><br><br>

Example Sentences (one example per line)
<br>
<textarea name="wordExample" cols="50" rows="5">
</textarea><br><br>
<input type="submit" value="Add Word" name="add"> 
{% if message_add == "Add word success" %}
<font color="green"><b>{{ message_add }}</b></font>
{% elif message_add == "Please fill input" %}
<font color="red"><b>{{ message_add }}</b></font>
{% endif %}
</form>
<br><br><br>

<h1>Upload word from CSV file</h1>
<form action="{% url 'WordBank:addword' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
Select CSV File:
<input type="file" name="csvFile" id="csvFile"><br><br>
<input type="submit" value="Upload CSV File" name="submit">
{% if message_upload_csv == "Upload word success" %}
<font color="green"><b>{{ message_upload_csv }}</b></font>
{% endif %}
</form><br>

<h1>Upload word from XML file</h1>
<form action="{% url 'WordBank:addword' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
Select XML File:
<input type="file" name="xmlFile" id="xmlFile"><br><br>
<input type="submit" value="Upload XML File" name="submit">
{% if message_upload_xml == "Upload word success" %}
<font color="green"><b>{{ message_upload_xml }}</b></font>
{% endif %}
</form><br>

<form action="{% url 'WordBank:backupandrestore' %}" method='POST'>
{% csrf_token %}
<input type="submit" value="Backup and Restore"> 
</form>


</body>
</html>

WordBank/templates/WordBank/allword.html
<html>
<head>
<title>Word Bank Website</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'WordBank/style.css' %}" />
</head>
<body>

<h1>All Word</h1>
{% if wordList %}
<center>
<div id='wordResult'>
<table id='wordResultTable'>
<tr id='header'>
<th id='wordText'>Word</td>
<th id='wordType'>Type</td>
<th id='wordMeaning'>Meaning</td>
<th id='wordExample'>Example sentences</td>
</tr>

{% for word in wordList %}
<tr id="{{ word.word_text }}">
<td name="wordText">{{ word.word_text}}</td>
	{% for type in word.wordtype_set.all %}
	{% if forloop.first %}
	<td name="wordType" >{{ type.word_type }}</td>
		{% for meaning in type.wordmeaning_set.all %}
		{% if forloop.first %}
		<td name="wordMeaning">{{ meaning.word_meaning }}</td>
			{% for example in meaning.wordexample_set.all %}
			{% if forloop.first %}
			<td name="wordExample">{{ example.word_example }}</td>
			{% else %}
			<tr>
			<td></td><td></td><td></td>
			<td name="wordExample">{{ example.word_example }}</td>
			</tr>
			{% endif %}
			{% endfor %}
		{% else %}
		<tr>
		<td></td><td></td>
		<td name="wordMeaning">{{ meaning.word_meaning }}</td>
			{% for example in meaning.wordexample_set.all %}
			{% if forloop.first %}
			<td name="wordExample">{{ example.word_example }}</td>
			{% else %}
			<tr>
			<td></td><td></td><td></td>
			<td name="wordExample">{{ example.word_example }}</td>
			</tr>
			{% endif %}
			{% endfor %}
		</tr>
		{% endif %}
		{% endfor %}
	{% else %}
	<tr>
	<td></td>
	<td name="wordType">{{ type.word_type }}</td>
		{% for meaning in type.wordmeaning_set.all %}
		{% if forloop.first %}
		<td name="wordMeaning">{{ meaning.word_meaning }}</td>
			{% for example in meaning.wordexample_set.all %}
			{% if forloop.first %}
			<td name="wordExample">{{ example.word_example }}</td>
			{% else %}
			<tr>
			<td></td><td></td><td></td>
			<td name="wordExample">{{ example.word_example }}</td>
			</tr>
			{% endif %}
			{% endfor %}
		{% else %}
		<tr>
		<td></td><td></td>
		<td name="wordMeaning">{{ meaning.word_meaning }}</td>
			{% for example in meaning.wordexample_set.all %}
			{% if forloop.first %}
			<td name="wordExample">{{ example.word_example }}</td>
			{% else %}
			<tr>
			<td></td><td></td><td></td>
			<td name="wordExample">{{ example.word_example }}</td>
			</tr>
			{% endif %}
			{% endfor %}
		</tr>
		{% endif %}
		{% endfor %}
	</tr>
	{% endif %}
	{% endfor %}
</tr>
{% endfor %}
</table>
</div>
<center>


{% else %}
    <p>Not found.</p>
{% endif %}

</body>
</html>

WordBank/templates/WordBank/backupandrestore.html
<html>
<head>
<title>Word Bank Website</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'WordBank/style.css' %}" />
</head>
<body>

<h1>Backup and Restore</h1>
<br>

<h2>Backup</h2>
<form action="{% url 'WordBank:backupandrestore' %}" method='POST'>
{% csrf_token %}
Backup Name : <input type="text" name="backup_name"><br><br>
<input type="submit" value="Backup to CSV" name='backup_csv'> 
<input type="submit" value="Backup to XML" name='backup_xml'> 
</form>
{% if message_backup == "Backup Success" %}
<font color="green"><b>{{ message_backup }}</b></font>
{% elif message_backup == "Backup Failed" %}
<font color="red"><b>{{ message_backup }}</b></font>
{% endif %}

<h2>Restore</h2>
<form action="{% url 'WordBank:backupandrestore' %}" method="post">
{% csrf_token %}
Select backup<br>
<select name="selectBackup" id='selectBackup' size=6>
	{% for backup in backup_list %}
    	<option value="{{ backup }}">{{ backup }}</option>
	{% endfor %}
</select><br><br>
<input type="submit" value="Restore" name="restore">
<input type="submit" value="Export" name="export"><br>
{% if message_restore == "Restore Success" %}
<font color="green"><b>{{ message_restore }}</b></font>
{% elif message_restore == "Restore Failed" %}
<font color="red"><b>{{ message_restore }}</b></font>
{% elif message_restore == "Please select backup for restore" %}
<font color="red"><b>{{ message_restore }}</b></font>
{% endif %}
</form>

<br><br>
<h2>Convert XML Normal Format/G2 Standard Format</h2>
<form action="{% url 'WordBank:backupandrestore' %}" method="post" enctype="multipart/form-data">
{% csrf_token %}
Select XML File:
<input type="file" name="xmlFile" id="xmlFile"><br><br>
<select name="convertType" id='convertType'>
	<option value="g2standard">Normal Format -> G2 Standard Format</option>
	<option value="normal">G2 Standard Format -> Normal Format</option>
</select><br><br>
<input type="submit" value="Convert" name="convertXMLstandard">
</form>

</body>
</html>

WordBank/templates/WordBank/index.html
<html>
<head>
<title>Word Bank Website</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'WordBank/style.css' %}" />
</head>
<body>

<br><br><br>
<div id='logo'>
<center><h1><b>Word Bank</b></h1></center>
</div>

<br><br>
<div id='searchBox'>
<center>
<form id="searchForm" action="{% url 'WordBank:result' %}" method='GET'>
<input type="text" name="wordInput" id="wordInput"> 
<input type="submit" value="Search" id="searchSubmit">
<br><br>
Search method : 
<select name="searchMethod" id='searchMethod'>
    <option value="any" id="any">Any</option>
    <option value="startWith" id="startWith">Start with</option>
    <option value="matchAll" id="matchAll">Match All</option>
</select>
</form>

<br><br>
<form action="{% url 'WordBank:addword' %}" method='GET'>
<input type="submit" value="Add Word"> 
</form>
<form action="{% url 'WordBank:allword' %}" method='GET'>
<input type="submit" value="All Word">
</form>
<form action="{% url 'WordBank:backupandrestore' %}" method='GET'>
<input type="submit" value="Backup and Restore"> 
</form>
<form action="{% url 'WordBank:showlastsearchkeyword' %}" method='GET'>
<input type="submit" value="Show Last Search Keyword"> 
</form>
<form action="{% url 'WordBank:showmostsearchword' %}" method='GET'>
<input type="submit" value="Show Most Search Word"> 
</form>

</center>
</div>

</body>
</html>

WordBank/templates/WordBank/result.html
<html>
<head>
<title>Word Bank Website</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'WordBank/style.css' %}" />
</head>
<body>

<div id='searchBox'>
<form action="{% url 'WordBank:result' %}" method='GET' id="searchForm">
<input type="text" name="wordInput"  id="wordInput" value="{{ wordInput }}"> 
<input type="submit" value="Search" id="searchSubmit">
<br><br>
Search method : 
<select name="searchMethod" id='searchMethod'>
    <option value="any" id="any">Any</option>
    <option value="startWith" id="startWith">Start with</option>
    <option value="matchAll" id="matchAll">Match All</option>
</select>
</form>
</div>

<br><br>

{% if wordList %}
<center>
<div id='wordResult'>
<table id='wordResultTable'>
<tr id='header'>
<th id='wordText'>Word</td>
<th id='wordType'>Type</td>
<th id='wordMeaning'>Meaning</td>
<th id='wordExample'>Example sentences</td>
</tr>

{% for word in wordList %}
<tr id="{{ word.word_text }}">
<td name="wordText">{{ word.word_text}}</td>
	{% for type in word.wordtype_set.all %}
	{% if forloop.first %}
	<td name="wordType" >{{ type.word_type }}</td>
		{% for meaning in type.wordmeaning_set.all %}
		{% if forloop.first %}
		<td name="wordMeaning">{{ meaning.word_meaning }}</td>
			{% for example in meaning.wordexample_set.all %}
			{% if forloop.first %}
			<td name="wordExample">{{ example.word_example }}</td>
			{% else %}
			<tr>
			<td></td><td></td><td></td>
			<td name="wordExample">{{ example.word_example }}</td>
			</tr>
			{% endif %}
			{% endfor %}
		{% else %}
		<tr>
		<td></td><td></td>
		<td name="wordMeaning">{{ meaning.word_meaning }}</td>
			{% for example in meaning.wordexample_set.all %}
			{% if forloop.first %}
			<td name="wordExample">{{ example.word_example }}</td>
			{% else %}
			<tr>
			<td></td><td></td><td></td>
			<td name="wordExample">{{ example.word_example }}</td>
			</tr>
			{% endif %}
			{% endfor %}
		</tr>
		{% endif %}
		{% endfor %}
	{% else %}
	<tr>
	<td></td>
	<td name="wordType">{{ type.word_type }}</td>
		{% for meaning in type.wordmeaning_set.all %}
		{% if forloop.first %}
		<td name="wordMeaning">{{ meaning.word_meaning }}</td>
			{% for example in meaning.wordexample_set.all %}
			{% if forloop.first %}
			<td name="wordExample">{{ example.word_example }}</td>
			{% else %}
			<tr>
			<td></td><td></td><td></td>
			<td name="wordExample">{{ example.word_example }}</td>
			</tr>
			{% endif %}
			{% endfor %}
		{% else %}
		<tr>
		<td></td><td></td>
		<td name="wordMeaning">{{ meaning.word_meaning }}</td>
			{% for example in meaning.wordexample_set.all %}
			{% if forloop.first %}
			<td name="wordExample">{{ example.word_example }}</td>
			{% else %}
			<tr>
			<td></td><td></td><td></td>
			<td name="wordExample">{{ example.word_example }}</td>
			</tr>
			{% endif %}
			{% endfor %}
		</tr>
		{% endif %}
		{% endfor %}
	</tr>
	{% endif %}
	{% endfor %}
</tr>
{% endfor %}
</table>
</div>
</center>

{% else %}
    <p>Not found.</p>
{% endif %}

</body>
</html>

WordBank/templates/WordBank/showLastSearchKeyword.html
<html>
<head>
<title>Word Bank Website</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'WordBank/style.css' %}" />
</head>
<body>

<h1>Last Search Keyword</h1>
{% if searchKeywordList %}
<center>
<div>
<table>
<tr>
<th>Keyword</td>
<th>Search Time</td>
<th>Found</td>
<th>Found Word</td>
</tr>

{% for searchKeyword in searchKeywordList %}
<tr>
<td>{{ searchKeyword.Search_Keyword }}</td>
<td>{{ searchKeyword.Search_Time }}</td>
<td>{{ searchKeyword.Found }}</td>
<td>
{% for word in searchKeyword.Found_Word %}
{% if forloop.first %}
{{ word }}
{% else %}
, {{ word }}
{% endif %}
{% endfor %}
</td>
</tr>
{% endfor %}
</table>
</div>
<center>


{% else %}
    <p>Not found.</p>
{% endif %}

</body>
</html>

WordBank/templates/WordBank/showMostSearchWord.html
<html>
<head>
<title>Word Bank Website</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'WordBank/style.css' %}" />
</head>
<body>

<h1>Most Search Word</h1>
{% if mostSearchWordList %}
<center>
<div>
<table>
<tr>
<th>Word</td>
<th>Search Times</td>
</tr>

{% for searchWord in mostSearchWordList %}
<tr>
<td>{{ searchWord.word }}</td>
<td>{{ searchWord.searchTimes }}</td>
</tr>
{% endfor %}
</table>
</div>
<center>


{% else %}
    <p>Not found.</p>
{% endif %}

</body>
</html>